addSbtPlugin("com.timushev.sbt"  %  "sbt-updates"           % "0.1.10")
addSbtPlugin("com.github.gseitz" %  "sbt-release"           % "1.0.1")
addSbtPlugin("org.scoverage"     %  "sbt-scoverage"         % "1.3.5")
addSbtPlugin("net.virtual-void"  %  "sbt-dependency-graph"  % "0.8.2")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "1.0.0")
